<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	<PropertyGroup>
		<Configurations>Developer;Release</Configurations>
		<Platforms>x64</Platforms>
		<TargetFrameworks>net48</TargetFrameworks>
		<AssemblyTitle>UIBlueprintEditorPlugin</AssemblyTitle>
		<Product>UIBlueprintEditorPlugin</Product>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<UseWPF>true</UseWPF>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Developer|x64'">
		<DebugSymbols>true</DebugSymbols>
		<OutputPath>bin\Developer\Debug\</OutputPath>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
		<OutputPath>bin\Release\Final\</OutputPath>
		<DefineConstants>TRACE</DefineConstants>
		<Optimize>true</Optimize>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Images\Grid.png" />
	  <None Remove="Images\IconBitmap.png" />
	  <None Remove="Images\IconFill.png" />
	  <None Remove="Images\IconOther.png" />
	  <None Remove="Images\IconText.png" />
	  <None Remove="Images\IconWidget.png" />
	  <None Remove="Images\Placeholder.png" />
	  <None Remove="Images\Precise_OFF.png" />
	  <None Remove="Images\Precise_ON.png" />
	  <None Remove="Images\Refresh.png" />
	  <None Remove="Images\Toolbox.png" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="FrostyControls">
		  <HintPath>..\..\gw2 stuff\FrostyEditor\FrostyControls.dll</HintPath>
		</Reference>
		<Reference Include="FrostyCore">
			<HintPath>D:\Documents\gw2 stuff\FrostyEditor\FrostyCore.dll</HintPath>
		</Reference>
		<Reference Include="FrostyHash">
		  <HintPath>..\..\gw2 stuff\FrostyEditor\FrostyHash.dll</HintPath>
		</Reference>
		<Reference Include="FrostySdk">
			<HintPath>D:\Documents\gw2 stuff\FrostyEditor\FrostySdk.dll</HintPath>
		</Reference>
		<Reference Include="LocalizedStringPlugin">
		  <HintPath>..\..\gw2 stuff\FrostyEditor\Plugins\LocalizedStringPlugin.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.CSharp" />
		<Reference Include="SharpDX.Direct3D11">
		  <HintPath>..\..\gw2 stuff\FrostyEditor\ThirdParty\SharpDX.Direct3D11.dll</HintPath>
		</Reference>
		<Reference Include="SharpDX.DXGI">
		  <HintPath>..\..\gw2 stuff\FrostyEditor\ThirdParty\SharpDX.DXGI.dll</HintPath>
		</Reference>
		<Reference Include="TexturePlugin">
		  <HintPath>..\..\gw2 stuff\FrostyEditor\Plugins\TexturePlugin.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Images\Grid.png" />
	  <Resource Include="Images\IconBitmap.png" />
	  <Resource Include="Images\IconFill.png" />
	  <Resource Include="Images\IconOther.png" />
	  <Resource Include="Images\IconText.png" />
	  <Resource Include="Images\IconWidget.png" />
	  <Resource Include="Images\Placeholder.png" />
	  <Resource Include="Images\Precise_OFF.png" />
	  <Resource Include="Images\Precise_ON.png" />
	  <Resource Include="Images\Refresh.png" />
	  <Resource Include="Images\Toolbox.png" />
	  <Resource Include="Images\UITypeIcon.png" />
	</ItemGroup>
</Project>