<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	<PropertyGroup>
		<Configurations>Developer - Debug;Release - Alpha;Release - Beta;Release - Final</Configurations>
		<Platforms>x64</Platforms>
		<TargetFrameworks>net48</TargetFrameworks>
		<AssemblyTitle>UIBlueprintEditorPlugin</AssemblyTitle>
		<Product>UIBlueprintEditorPlugin</Product>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<UseWPF>true</UseWPF>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Developer - Debug|x64' ">
		<DebugSymbols>true</DebugSymbols>
		<OutputPath>bin\Developer\Debug\</OutputPath>
		<DefineConstants>TRACE;DEBUG;DEVELOPER_DEBUG</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release - Alpha|x64' ">
		<OutputPath>bin\Release\Alpha\</OutputPath>
		<DefineConstants>TRACE</DefineConstants>
		<Optimize>true</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Beta|x64'">
		<OutputPath>bin\Release\Beta\</OutputPath>
		<DefineConstants>TRACE</DefineConstants>
		<Optimize>true</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Final|x64'">
		<OutputPath>bin\Release\Final\</OutputPath>
		<DefineConstants>TRACE</DefineConstants>
		<Optimize>true</Optimize>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy /Y $(TargetPath) $(SolutionDir)$(OutDir)Plugins\" />
	</Target>

	<ItemGroup>
	  <None Remove="Images\Grid.png" />
	  <None Remove="Images\IconBitmap.png" />
	  <None Remove="Images\IconFill.png" />
	  <None Remove="Images\IconOther.png" />
	  <None Remove="Images\IconText.png" />
	  <None Remove="Images\IconWidget.png" />
	  <None Remove="Images\Placeholder.png" />
	  <None Remove="Images\Precise_OFF.png" />
	  <None Remove="Images\Precise_ON.png" />
	  <None Remove="Images\Refresh.png" />
	  <None Remove="Images\Toolbox.png" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\FrostyControls\FrostyControls.csproj" />
	  <ProjectReference Include="..\..\FrostyHash\FrostyHash.vcxproj" />
	  <ProjectReference Include="..\..\FrostyPlugin\FrostyCore.csproj" />
	  <ProjectReference Include="..\..\FrostySdk\FrostySdk.csproj" />
	  <ProjectReference Include="..\LocalizedStringPlugin\LocalizedStringPlugin.csproj" />
	  <ProjectReference Include="..\TexturePlugin\TexturePlugin.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Microsoft.CSharp" />
		<Reference Include="SharpDX.Direct3D11">
		  <HintPath>..\..\FrostyEditor\bin\Developer\Debug\ThirdParty\SharpDX.Direct3D11.dll</HintPath>
		</Reference>
		<Reference Include="SharpDX.DXGI">
		  <HintPath>..\..\FrostyEditor\bin\Developer\Debug\ThirdParty\SharpDX.DXGI.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Images\Grid.png" />
	  <Resource Include="Images\IconBitmap.png" />
	  <Resource Include="Images\IconFill.png" />
	  <Resource Include="Images\IconOther.png" />
	  <Resource Include="Images\IconText.png" />
	  <Resource Include="Images\IconWidget.png" />
	  <Resource Include="Images\Placeholder.png" />
	  <Resource Include="Images\Precise_OFF.png" />
	  <Resource Include="Images\Precise_ON.png" />
	  <Resource Include="Images\Refresh.png" />
	  <Resource Include="Images\Toolbox.png" />
	  <Resource Include="Images\UITypeIcon.png" />
	</ItemGroup>
</Project>